import type { Article } from '@/types/article'

const d = (daysAgo: number) => {
  const dt = new Date()
  dt.setDate(dt.getDate() - daysAgo)
  return dt.toISOString().split('T')[0]
}

export const MOCK_ARTICLES: Article[] = [

  // ── Revista Electricidad ─────────────────────────────────
  {
    id: 'mock-rev-elec-001',
    title: 'Chile alcanza 30% de generación renovable en el Sistema Eléctrico Nacional',
    title_es: 'Chile alcanza 30% de generación renovable en el Sistema Eléctrico Nacional',
    source: 'Revista Electricidad',
    source_type: 'Press',
    location: 'Chile',
    category: 'Energy',
    date: d(1),
    url: 'https://www.revistaei.cl/2024/generacion-renovable-30-porciento',
    extended_description: 'El Sistema Eléctrico Nacional de Chile superó el 30% de participación de energías renovables no convencionales durante el primer semestre, según datos del Coordinador Eléctrico Nacional. La solar fotovoltaica lidera el crecimiento con 12 GW instalados, seguida por la eólica con 4,8 GW. Este hito posiciona al país como referente regional en transición energética, aunque persisten desafíos de almacenamiento y gestión de excedentes en horas de alta irradiación.',
    extended_description_es: 'El Sistema Eléctrico Nacional de Chile superó el 30% de participación de energías renovables no convencionales durante el primer semestre, según datos del Coordinador Eléctrico Nacional. La solar fotovoltaica lidera el crecimiento con 12 GW instalados, seguida por la eólica con 4,8 GW. Este hito posiciona al país como referente regional en transición energética, aunque persisten desafíos de almacenamiento y gestión de excedentes.',
    short_summary: [
      'Chile surpasses 30% renewable share in national grid, led by 12 GW of solar PV capacity.',
      'Wind energy adds 4.8 GW, consolidating Chile as a regional clean energy benchmark.',
      'Storage gaps and surplus management remain key challenges for further NCRE integration.',
    ],
    short_summary_es: [
      'Chile supera 30% de participación renovable en el SEN, liderado por 12 GW solares.',
      'La eólica aporta 4,8 GW, consolidando a Chile como referente regional.',
      'La gestión de excedentes y el almacenamiento siguen siendo los principales desafíos.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },
  {
    id: 'mock-rev-elec-002',
    title: 'Nuevas licitaciones de transmisión eléctrica suman 1.200 km de líneas al norte del país',
    title_es: 'Nuevas licitaciones de transmisión eléctrica suman 1.200 km de líneas al norte del país',
    source: 'Revista Electricidad',
    source_type: 'Press',
    location: 'Chile',
    category: 'Energy',
    date: d(3),
    url: 'https://www.revistaei.cl/2024/licitaciones-transmision-norte',
    extended_description: 'El Ministerio de Energía lanzó un proceso de licitación para construir 1.200 km de nuevas líneas de transmisión de alta tensión en las regiones de Tarapacá y Antofagasta. El proyecto busca evacuar la creciente generación solar del norte grande hacia los centros de consumo del centro-sur del país. La inversión estimada supera los US$800 millones y contempla tecnología HVDC para reducir pérdidas en el transporte de largo aliento.',
    extended_description_es: 'El Ministerio de Energía lanzó un proceso de licitación para construir 1.200 km de nuevas líneas de transmisión de alta tensión en las regiones de Tarapacá y Antofagasta. El proyecto busca evacuar la creciente generación solar del norte grande hacia los centros de consumo del centro-sur del país.',
    short_summary: [
      'Chile tenders 1,200 km of new high-voltage transmission lines in Tarapacá and Antofagasta regions.',
      'Project aims to evacuate surplus solar generation from the Atacama north to central consumption hubs.',
      'HVDC technology included to minimize long-distance transmission losses; estimated cost US$800M.',
    ],
    short_summary_es: [
      'Chile licita 1.200 km de nuevas líneas de alta tensión en el norte del país.',
      'El proyecto evacuará excedentes solares del norte grande hacia centros de consumo.',
      'Se contempla tecnología HVDC; inversión estimada supera los US$800 millones.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },

  // ── Diario Financiero ────────────────────────────────────
  {
    id: 'mock-df-001',
    title: 'Inversión extranjera en minería chilena crece 18% en primer semestre impulsada por cobre y litio',
    title_es: 'Inversión extranjera en minería chilena crece 18% en primer semestre impulsada por cobre y litio',
    source: 'Diario Financiero',
    source_type: 'Press',
    location: 'Chile',
    category: 'Mining',
    date: d(1),
    url: 'https://www.df.cl/mercados/mineria/inversion-extranjera-mineria-primer-semestre',
    extended_description: 'La inversión extranjera directa en el sector minero chileno creció 18% interanual durante el primer semestre, alcanzando US$3.200 millones según cifras del Ministerio de Minería. El cobre concentró el 67% de los flujos, mientras el litio atrajo US$680 millones de capitales australianos, canadienses y chinos. Los analistas destacan que Chile mantiene su ventaja competitiva pese a la incertidumbre regulatoria, gracias a la infraestructura consolidada y la calidad de sus reservas.',
    extended_description_es: 'La inversión extranjera directa en el sector minero chileno creció 18% interanual durante el primer semestre, alcanzando US$3.200 millones. El cobre concentró el 67% de los flujos, mientras el litio atrajo US$680 millones de capitales australianos, canadienses y chinos.',
    short_summary: [
      'Foreign mining investment in Chile grew 18% YoY to US$3.2 billion in H1, driven by copper and lithium.',
      'Lithium attracted US$680M from Australian, Canadian, and Chinese capital amid global EV demand.',
      'Chile maintains competitive edge despite regulatory uncertainty due to infrastructure quality.',
    ],
    short_summary_es: [
      'La IED minera en Chile creció 18% interanual hasta US$3.200 millones en el primer semestre.',
      'El litio atrajo US$680 millones de capitales australianos, canadienses y chinos.',
      'Chile mantiene ventaja competitiva pese a la incertidumbre regulatoria.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },
  {
    id: 'mock-df-002',
    title: 'Precio del cobre supera los US$4,5 la libra por tensiones en oferta y demanda de IA',
    title_es: 'Precio del cobre supera los US$4,5 la libra por tensiones en oferta y demanda de IA',
    source: 'Diario Financiero',
    source_type: 'Press',
    location: 'Chile',
    category: 'Mining',
    date: d(2),
    url: 'https://www.df.cl/mercados/commodities/precio-cobre-ai-demanda',
    extended_description: 'El precio del cobre en la Bolsa de Metales de Londres superó los US$4,5 por libra, impulsado por la demanda de infraestructura para centros de datos de inteligencia artificial y el déficit de inventarios en almacenes LME. Analistas de Goldman Sachs proyectan que la demanda acumulada de cobre por parte del sector tecnológico superará los 5 millones de toneladas anuales hacia 2030. Chile, como mayor productor mundial, enfrenta presión para acelerar proyectos greenfield que hoy están frenados por aprobaciones ambientales.',
    extended_description_es: 'El precio del cobre en la LME superó los US$4,5 por libra, impulsado por la demanda de infraestructura para centros de datos de IA y el déficit de inventarios. Goldman Sachs proyecta que la demanda acumulada de cobre por el sector tecnológico superará los 5 millones de toneladas anuales hacia 2030.',
    short_summary: [
      'Copper breaks US$4.5/lb on LME driven by AI data center infrastructure demand and low inventories.',
      'Goldman Sachs projects tech sector copper demand exceeding 5 million tonnes annually by 2030.',
      'Chile faces pressure to accelerate greenfield approvals as the world\'s leading copper producer.',
    ],
    short_summary_es: [
      'El cobre supera US$4,5/lb en la LME por demanda de infraestructura para IA e inventarios bajos.',
      'Goldman Sachs proyecta demanda de cobre del sector tecnológico superando 5 Mt/año hacia 2030.',
      'Chile enfrenta presión para acelerar aprobaciones de proyectos greenfield.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },
  {
    id: 'mock-df-003',
    title: 'Enel Chile anuncia plan de inversión de US$1.800 millones en renovables y almacenamiento',
    title_es: 'Enel Chile anuncia plan de inversión de US$1.800 millones en renovables y almacenamiento',
    source: 'Diario Financiero',
    source_type: 'Press',
    location: 'Chile',
    category: 'Energy',
    date: d(4),
    url: 'https://www.df.cl/empresas/energia/enel-chile-plan-inversion-renovables',
    extended_description: 'Enel Chile presentó su plan estratégico 2024-2027 con una inversión de US$1.800 millones destinados a expandir su capacidad de generación renovable en 2.400 MW adicionales y desplegar 600 MWh de baterías de almacenamiento de gran escala en la Región Metropolitana y el norte del país. El plan contempla el cierre anticipado de las últimas unidades a carbón de la empresa y refuerza su apuesta por la flexibilidad de red como servicio complementario al mercado spot.',
    extended_description_es: 'Enel Chile presentó su plan estratégico 2024-2027 con una inversión de US$1.800 millones para expandir 2.400 MW renovables y desplegar 600 MWh de baterías de almacenamiento de gran escala.',
    short_summary: [
      'Enel Chile commits US$1.8 billion to add 2,400 MW renewables and 600 MWh grid-scale storage by 2027.',
      'Plan includes early retirement of remaining coal units and grid flexibility services expansion.',
      'Battery deployment targets Metropolitan Region and Atacama north to address solar curtailment.',
    ],
    short_summary_es: [
      'Enel Chile destina US$1.800 millones para añadir 2.400 MW renovables y 600 MWh de baterías al 2027.',
      'El plan incluye el cierre anticipado de las últimas unidades a carbón de la empresa.',
      'El despliegue de baterías apunta a la RM y el norte para reducir el vertimiento solar.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },

  // ── La Tercera ──────────────────────────────────────────
  {
    id: 'mock-lt-001',
    title: 'Gobierno anuncia plan nacional de hidrógeno verde con meta de 25 GW al 2030',
    title_es: 'Gobierno anuncia plan nacional de hidrógeno verde con meta de 25 GW al 2030',
    source: 'La Tercera',
    source_type: 'Press',
    location: 'Chile',
    category: 'Energy',
    date: d(1),
    url: 'https://www.latercera.com/pulso/noticia/gobierno-hidrogeno-verde-25gw-2030',
    extended_description: 'El Ministerio de Energía presentó la Estrategia Nacional de Hidrógeno Verde con una meta de producción de 25 GW de electrólisis al año 2030, posicionando a Chile entre los cinco mayores exportadores potenciales del mundo. El plan contempla zonas de desarrollo preferente en Magallanes, Atacama y Tarapacá, y prevé atraer US$20.000 millones en inversión privada mediante contratos de largo plazo con compradores europeos y asiáticos. La brecha de costos frente al hidrógeno gris se estima en US$1,5/kg y se espera cerrar hacia 2027.',
    extended_description_es: 'El Ministerio de Energía presentó la Estrategia Nacional de Hidrógeno Verde con meta de 25 GW de electrólisis al 2030. El plan contempla zonas de desarrollo en Magallanes, Atacama y Tarapacá, y prevé atraer US$20.000 millones en inversión privada.',
    short_summary: [
      'Chile targets 25 GW of green hydrogen electrolysis capacity by 2030 under new national strategy.',
      'Preferred development zones in Magallanes, Atacama, and Tarapacá target European and Asian buyers.',
      'Cost gap vs. grey hydrogen estimated at US$1.5/kg, expected to close by 2027 at scale.',
    ],
    short_summary_es: [
      'Chile apunta a 25 GW de electrólisis de hidrógeno verde al 2030 con nueva estrategia nacional.',
      'Zonas de desarrollo en Magallanes, Atacama y Tarapacá apuntan a compradores europeos y asiáticos.',
      'La brecha de costos frente al H2 gris es de US$1,5/kg y se espera cerrar hacia 2027.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },
  {
    id: 'mock-lt-002',
    title: 'SQM reporta caída de 42% en utilidades por desplome del precio del litio',
    title_es: 'SQM reporta caída de 42% en utilidades por desplome del precio del litio',
    source: 'La Tercera',
    source_type: 'Press',
    location: 'Chile',
    category: 'Mining',
    date: d(2),
    url: 'https://www.latercera.com/pulso/noticia/sqm-caida-utilidades-litio',
    extended_description: 'SQM reportó una caída de 42% en sus utilidades netas durante el segundo trimestre, reflejando la presión sobre los precios del litio que han retrocedido más de 70% desde su peak de 2022. La compañía mantiene su guidance de producción en 190.000 toneladas de LCE y apuesta por la diversificación hacia yodo y nitratos para compensar el impacto. El directorio anunció una revisión de su política de dividendos y un programa de eficiencia que busca reducir costos operacionales en 15%.',
    extended_description_es: 'SQM reportó una caída de 42% en utilidades netas en el segundo trimestre por la presión sobre precios del litio. La compañía mantiene su guidance de 190.000 t de LCE y apuesta por diversificación en yodo y nitratos para compensar el impacto.',
    short_summary: [
      'SQM reports 42% net profit decline in Q2 as lithium prices remain 70% below 2022 peak.',
      'Production guidance maintained at 190,000 tonnes LCE; iodine and nitrates to offset lithium losses.',
      'Board announces dividend review and 15% cost reduction program to preserve balance sheet.',
    ],
    short_summary_es: [
      'SQM reporta caída de 42% en utilidades Q2 con precios del litio un 70% por debajo del peak.',
      'El guidance de producción se mantiene en 190.000 t LCE; yodo y nitratos compensarán el impacto.',
      'El directorio revisa política de dividendos y anuncia programa de reducción de costos del 15%.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },

  // ── Emol ────────────────────────────────────────────────
  {
    id: 'mock-emol-001',
    title: 'Chile aprobó proyecto de ley de almacenamiento energético que facilita baterías de gran escala',
    title_es: 'Chile aprobó proyecto de ley de almacenamiento energético que facilita baterías de gran escala',
    source: 'Emol',
    source_type: 'Press',
    location: 'Chile',
    category: 'Energy',
    date: d(1),
    url: 'https://www.emol.com/noticias/Economia/2024/ley-almacenamiento-energetico',
    extended_description: 'La Cámara de Diputados aprobó en tercer trámite el proyecto de ley de almacenamiento de energía, que establece un marco regulatorio específico para baterías y otros sistemas de almacenamiento conectados al Sistema Eléctrico Nacional. La ley define los servicios complementarios que pueden prestar estos sistemas, su tratamiento tarifario y los incentivos para su desarrollo. Especialistas estiman que podría detonar inversiones superiores a US$2.000 millones en la próxima década.',
    extended_description_es: 'La Cámara de Diputados aprobó el proyecto de ley de almacenamiento de energía, que establece un marco regulatorio para baterías y sistemas de almacenamiento en el SEN. La ley define servicios complementarios, tratamiento tarifario e incentivos.',
    short_summary: [
      'Chile\'s Chamber of Deputies passes landmark energy storage law establishing grid-scale battery framework.',
      'Law defines ancillary services, tariff treatment, and development incentives for storage operators.',
      'Analysts project over US$2 billion in storage investment triggered by new regulatory certainty.',
    ],
    short_summary_es: [
      'Chile aprueba ley de almacenamiento energético que crea marco regulatorio para baterías de gran escala.',
      'La ley define servicios complementarios, tarifas e incentivos para operadores de almacenamiento.',
      'Analistas proyectan más de US$2.000 millones en inversión por la nueva certeza regulatoria.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },
  {
    id: 'mock-emol-002',
    title: 'Codelco registra pérdidas operacionales por alza de costos y menor ley de mineral',
    title_es: 'Codelco registra pérdidas operacionales por alza de costos y menor ley de mineral',
    source: 'Emol',
    source_type: 'Press',
    location: 'Chile',
    category: 'Mining',
    date: d(3),
    url: 'https://www.emol.com/noticias/Economia/2024/codelco-perdidas-costos',
    extended_description: 'Codelco reportó pérdidas operacionales de US$219 millones en el primer semestre, resultado de la combinación entre el alza de costos de energía y mano de obra, y la caída sostenida en las leyes de mineral en sus principales yacimientos. El costo C1 promedio escaló a US$1,82 por libra, superando la media de la industria. La empresa estatal aceleró su programa de transformación estructural que busca recuperar competitividad antes de 2026 mediante automatización y revisión de contratos de terceros.',
    extended_description_es: 'Codelco reportó pérdidas operacionales de US$219 millones en el primer semestre por alza de costos y menor ley de mineral. El costo C1 escaló a US$1,82/lb, sobre la media de la industria.',
    short_summary: [
      'Codelco posts US$219M operating loss in H1 as C1 costs climb to US$1.82/lb above industry average.',
      'Rising energy and labor costs compound declining ore grades at flagship mines.',
      'Structural transformation program targets competitiveness recovery by 2026 via automation.',
    ],
    short_summary_es: [
      'Codelco reporta pérdidas operacionales de US$219M en H1 con costo C1 en US$1,82/lb.',
      'El alza de costos de energía y mano de obra se combina con menor ley de mineral.',
      'El programa de transformación apunta a recuperar competitividad antes de 2026 con automatización.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },

  // ── Economía y Negocios (El Mercurio) ────────────────────
  {
    id: 'mock-eyn-001',
    title: 'Tarifas eléctricas industriales bajarán 12% en próximo proceso de tarificación',
    title_es: 'Tarifas eléctricas industriales bajarán 12% en próximo proceso de tarificación',
    source: 'Economia y Negocios',
    source_type: 'Press',
    location: 'Chile',
    category: 'Energy',
    date: d(2),
    url: 'https://www.economiaynegocios.cl/noticias/noticias.asp?id=tarifas-electricas-bajan',
    extended_description: 'La Comisión Nacional de Energía informó que las tarifas eléctricas para clientes industriales registrarán una reducción promedio de 12% en el siguiente período tarifario, reflejo de la mayor penetración renovable y la caída en los precios del gas natural licuado. Las empresas mineras de la zona norte son las principales beneficiadas, con reducciones que podrían superar el 18% en algunos nodos del sistema. La medida abarata los costos operacionales del sector y mejora la competitividad de la producción nacional de cobre.',
    extended_description_es: 'La CNE informó que las tarifas eléctricas industriales bajarán un promedio de 12% en el siguiente período tarifario, por mayor penetración renovable y caída del GNL. Las mineras del norte son las principales beneficiadas.',
    short_summary: [
      'CNE confirms 12% average reduction in industrial electricity tariffs for next regulatory period.',
      'Mining companies in northern Chile to benefit most, with cuts exceeding 18% at some grid nodes.',
      'Lower power costs improve competitiveness of Chilean copper production vs. global peers.',
    ],
    short_summary_es: [
      'CNE confirma rebaja promedio del 12% en tarifas eléctricas industriales para el próximo período.',
      'Las mineras del norte serán las más beneficiadas, con rebajas superiores al 18% en algunos nodos.',
      'Los menores costos eléctricos mejoran la competitividad de la producción de cobre frente a pares globales.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },
  {
    id: 'mock-eyn-002',
    title: 'Data centers en Chile suman 300 MW de capacidad instalada ante auge de IA',
    title_es: 'Data centers en Chile suman 300 MW de capacidad instalada ante auge de IA',
    source: 'Economia y Negocios',
    source_type: 'Press',
    location: 'Chile',
    category: 'Data Centers',
    date: d(3),
    url: 'https://www.economiaynegocios.cl/noticias/noticias.asp?id=data-centers-300mw',
    extended_description: 'La capacidad instalada de centros de datos en Chile alcanzó los 300 MW, con 12 nuevos proyectos en construcción que agregarán otros 180 MW antes de fines de 2025, según un reporte del sector tecnológico. El crecimiento es impulsado por la llegada de hiperescaladores internacionales que ven en Chile condiciones ventajosas: estabilidad política, fibra submarina y energía renovable abundante. La demanda de energía del sector podría representar el 8% del consumo eléctrico total del país hacia 2028.',
    extended_description_es: 'La capacidad instalada de centros de datos en Chile alcanzó los 300 MW, con 12 nuevos proyectos que agregarán 180 MW antes de fines de 2025. El crecimiento es impulsado por hiperescaladores internacionales atraídos por la estabilidad y la energía renovable.',
    short_summary: [
      'Chile reaches 300 MW installed data center capacity with 12 projects adding 180 MW by end-2025.',
      'Hyperscalers cite political stability, subsea fiber, and abundant renewables as key location drivers.',
      'Sector electricity demand could reach 8% of Chile\'s total consumption by 2028.',
    ],
    short_summary_es: [
      'Chile alcanza 300 MW de capacidad instalada en centros de datos con 12 proyectos adicionales.',
      'Los hiperescaladores destacan la estabilidad, fibra submarina y energía renovable como factores clave.',
      'La demanda eléctrica del sector podría representar el 8% del consumo total del país hacia 2028.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },

  // ── Global sources ───────────────────────────────────────
  {
    id: 'mock-iea-001',
    title: 'IEA: Global clean energy investment set to exceed $2 trillion for first time in 2024',
    title_es: 'AIE: La inversión global en energía limpia superará los 2 billones de dólares por primera vez en 2024',
    source: 'IEA',
    source_type: 'Institutional',
    location: 'Global',
    category: 'Energy',
    date: d(1),
    url: 'https://www.iea.org/news/clean-energy-investment-2024',
    extended_description: 'The International Energy Agency reports global clean energy investment is on track to surpass $2 trillion in 2024, with solar and wind accounting for roughly $1.1 trillion. Emerging markets in Latin America and Southeast Asia show accelerated growth driven by declining technology costs. The milestone represents a doubling of clean-energy spending in five years. Grid infrastructure and storage remain the most under-invested segments relative to what the energy transition requires.',
    extended_description_es: 'La Agencia Internacional de Energía informa que la inversión mundial en energía limpia superará los 2 billones de dólares en 2024, con solar y eólica representando 1,1 billones. Los mercados emergentes en América Latina muestran crecimiento acelerado.',
    short_summary: [
      'Global clean energy investment hits $2 trillion milestone in 2024, led by $1.1T in solar and wind.',
      'Latin America and Southeast Asia emerge as fastest-growing markets due to lower technology costs.',
      'Grid infrastructure and storage remain critically underfunded relative to net-zero requirements.',
    ],
    short_summary_es: [
      'La inversión global en energía limpia alcanza 2 billones en 2024, liderada por solar y eólica.',
      'América Latina y el Sudeste Asiático son los mercados de más rápido crecimiento.',
      'La infraestructura de redes y el almacenamiento siguen siendo insuficientes para la transición.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },
  {
    id: 'mock-mining-001',
    title: 'Mining.com: Copper deficit widens as AI infrastructure boom accelerates demand',
    title_es: 'Déficit de cobre se amplía a medida que el auge de infraestructura IA acelera la demanda',
    source: 'Mining.com',
    source_type: 'Press',
    location: 'Global',
    category: 'Mining',
    date: d(2),
    url: 'https://www.mining.com/copper-deficit-ai-infrastructure-2024/',
    extended_description: 'A structural copper deficit is widening as AI-driven data center construction accelerates demand for the metal beyond supply growth projections. Goldman Sachs estimates the market could face a 500,000-tonne shortfall by 2026 if major greenfield projects remain delayed. Chile and Peru together account for 40% of global supply, making permitting timelines in both countries critical to whether the deficit triggers sustained price appreciation.',
    extended_description_es: 'Un déficit estructural de cobre se amplía a medida que la construcción de centros de datos impulsada por IA acelera la demanda más allá de las proyecciones de oferta. Goldman Sachs estima un déficit de 500.000 t para 2026 si los proyectos greenfield permanecen retrasados.',
    short_summary: [
      'Structural copper deficit widens to potential 500,000t by 2026 as AI data centers accelerate demand.',
      'Chile and Peru supply 40% of global copper; permitting timelines are critical to price trajectory.',
      'Goldman Sachs warns sustained greenfield delays could trigger multi-year price appreciation.',
    ],
    short_summary_es: [
      'El déficit estructural de cobre podría alcanzar 500.000 t para 2026 por demanda de centros de datos IA.',
      'Chile y Perú aportan el 40% de la oferta global; los plazos de permisos son críticos.',
      'Goldman Sachs advierte que los retrasos en proyectos greenfield podrían generar apreciación plurianual.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },
  {
    id: 'mock-dcd-001',
    title: 'Data Center Dynamics: Hyperscalers commit $50B to Latin American DC expansion through 2027',
    title_es: 'Hiperescaladores comprometen US$50.000M en expansión de centros de datos en Latinoamérica hasta 2027',
    source: 'Data Center Dynamics',
    source_type: 'Press',
    location: 'Global',
    category: 'Data Centers',
    date: d(1),
    url: 'https://www.datacenterdynamics.com/latam-hyperscaler-expansion-2027/',
    extended_description: 'Amazon Web Services, Microsoft Azure, and Google Cloud have collectively announced over $50 billion in planned data center investments across Latin America through 2027, with Chile, Brazil, and Mexico as primary deployment markets. The accelerated timeline is driven by AI workload demand, data sovereignty regulations, and improving subsea cable connectivity. Chile emerges as a preferred hub due to political stability, renewable energy abundance, and favorable cooling conditions.',
    extended_description_es: 'AWS, Azure y Google Cloud anunciaron conjuntamente más de US$50.000 millones en inversiones en centros de datos en Latinoamérica hasta 2027, con Chile, Brasil y México como principales mercados.',
    short_summary: [
      'AWS, Azure, and Google commit $50B to Latin American data center expansion through 2027.',
      'Chile leads regional appeal: political stability, renewables, and favorable cooling conditions.',
      'AI workload growth and data sovereignty regulations are the primary investment drivers.',
    ],
    short_summary_es: [
      'AWS, Azure y Google comprometen US$50.000M en expansión de centros de datos en Latinoamérica hasta 2027.',
      'Chile lidera el atractivo regional por estabilidad, energía renovable y condiciones de refrigeración.',
      'El crecimiento de IA y las regulaciones de soberanía de datos son los principales impulsores.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },
  {
    id: 'mock-cochilco-001',
    title: 'Cochilco proyecta producción de cobre de 5,7 Mt para 2024 con leve recuperación en H2',
    title_es: 'Cochilco proyecta producción de cobre de 5,7 Mt para 2024 con leve recuperación en H2',
    source: 'Cochilco',
    source_type: 'Institutional',
    location: 'Chile',
    category: 'Mining',
    date: d(2),
    url: 'https://www.cochilco.cl/Listado%20Materias/proyeccion-produccion-cobre-2024.pdf',
    extended_description: 'La Comisión Chilena del Cobre proyecta una producción nacional de 5,7 millones de toneladas métricas de cobre fino para 2024, con una leve recuperación esperada en el segundo semestre tras los problemas operacionales del primer half. Escondida y Collahuasi son los yacimientos que liderarán la recuperación. Cochilco anticipa que Chile recuperará su participación del 27% en la oferta global hacia fines de año, luego del deterioro observado en los últimos tres periodos.',
    extended_description_es: 'Cochilco proyecta producción de 5,7 Mt de cobre fino para 2024, con recuperación en H2 liderada por Escondida y Collahuasi. Chile recuperaría su participación del 27% en la oferta global.',
    short_summary: [
      'Cochilco projects 5.7Mt copper output for 2024 with H2 recovery led by Escondida and Collahuasi.',
      'Chile targets recovery of 27% global supply share after deterioration in recent periods.',
      'Operational issues in H1 at major mines expected to be resolved through Q3 maintenance campaigns.',
    ],
    short_summary_es: [
      'Cochilco proyecta 5,7 Mt de cobre para 2024 con recuperación en H2 por Escondida y Collahuasi.',
      'Chile apunta a recuperar su participación del 27% en la oferta global.',
      'Los problemas operacionales del H1 se espera resolver en campañas de mantenimiento del Q3.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },

  // ── ACERA (Conglomerado) ─────────────────────────────────
  {
    id: 'mock-acera-001',
    title: 'ACERA: Chile installed solar capacity reaches 15 GW milestone in Q2',
    title_es: 'ACERA: Chile supera los 15 GW de capacidad solar instalada en el segundo trimestre',
    source: 'ACERA',
    source_type: 'Conglomerado',
    location: 'Chile',
    category: 'Energy',
    date: d(2),
    url: 'https://www.acera.cl/noticias/capacidad-solar-15gw',
    extended_description: 'La Asociacion Chilena de Energias Renovables y Almacenamiento reporto que Chile alcanzo el hito de 15 GW de capacidad solar fotovoltaica instalada al cierre del segundo trimestre, consolidando al pais como el mayor mercado solar per capita de America Latina. El 68% de la nueva capacidad corresponde a proyectos utility-scale en las regiones de Antofagasta y Atacama.',
    extended_description_es: 'ACERA reporto que Chile alcanzo el hito de 15 GW de capacidad solar fotovoltaica instalada al cierre del segundo trimestre, consolidando al pais como el mayor mercado solar per capita de America Latina.',
    short_summary: [
      'Chile surpasses 15 GW solar milestone in Q2, leading Latin America in per-capita solar capacity.',
      '68% of new capacity is utility-scale projects in Antofagasta and Atacama regions.',
      'ACERA urges grid storage investment to absorb growing solar surplus during peak generation hours.',
    ],
    short_summary_es: [
      'Chile supera los 15 GW solares en Q2, liderando America Latina en capacidad per capita.',
      'El 68% de la nueva capacidad son proyectos utility-scale en Antofagasta y Atacama.',
      'ACERA urge invertir en almacenamiento para absorber los excedentes solares en horas pico.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },

  // ── ACENOR (Conglomerado) ────────────────────────────────
  {
    id: 'mock-acenor-001',
    title: 'ACENOR proposes regulatory reform to accelerate small hydro and run-of-river projects',
    title_es: 'ACENOR propone reforma regulatoria para acelerar proyectos hidro de pasada en Chile',
    source: 'ACENOR',
    source_type: 'Conglomerado',
    location: 'Chile',
    category: 'Energy',
    date: d(4),
    url: 'https://www.acenor.cl/noticias/reforma-regulatoria-hidro-pasada',
    extended_description: 'ACENOR presento ante la Comision Nacional de Energia una propuesta de reforma regulatoria para simplificar los permisos ambientales de proyectos hidroelectricos de pasada menores a 20 MW. La asociacion argumenta que estos proyectos ofrecen generacion de bajo impacto ambiental y complementan la variabilidad solar y eolica al proveer potencia firme durante las noches.',
    extended_description_es: 'ACENOR presento una propuesta de reforma para simplificar permisos de proyectos hidro de pasada menores a 20 MW, argumentando que proveen potencia firme complementaria a solar y eolica.',
    short_summary: [
      'ACENOR submits regulatory reform proposal to CNE to fast-track small hydro under 20 MW.',
      'Run-of-river projects provide firm nighttime power that complements solar and wind variability.',
      'Current permitting process takes 4-7 years for small hydro vs. under 2 years for solar PV.',
    ],
    short_summary_es: [
      'ACENOR presenta reforma a CNE para agilizar permisos de hidro de pasada menores a 20 MW.',
      'Proyectos de pasada proveen potencia firme nocturna que complementa solar y eolica.',
      'El proceso actual toma 4-7 anos para hidro pequena versus menos de 2 anos para solar.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },

  // ── SOFOFA (Conglomerado) ────────────────────────────────
  {
    id: 'mock-sofofa-001',
    title: 'SOFOFA: Industrial energy costs remain key barrier to Chilean competitiveness',
    title_es: 'SOFOFA: Los costos energeticos industriales siguen siendo barrera para la competitividad chilena',
    source: 'SOFOFA',
    source_type: 'Conglomerado',
    location: 'Chile',
    category: 'Energy',
    date: d(3),
    url: 'https://www.sofofa.cl/noticias/costos-energeticos-competitividad',
    extended_description: 'La Sociedad de Fomento Fabril publico un informe destacando que los costos energeticos industriales en Chile son un 35% superiores al promedio de la OCDE, afectando la competitividad del sector manufacturero y minero. SOFOFA propone acelerar el despliegue de almacenamiento a gran escala y revisar los cargos de transmision para distribuir los costos mas equitativamente entre todos los sectores consumidores.',
    extended_description_es: 'SOFOFA publico un informe destacando que los costos energeticos industriales en Chile son un 35% superiores al promedio OCDE, afectando la competitividad del sector manufacturero y minero.',
    short_summary: [
      'SOFOFA report finds Chilean industrial energy costs 35% above OECD average, hurting competitiveness.',
      'Manufacturing and mining sectors most affected; calls for transmission cost redistribution.',
      'Accelerating large-scale storage deployment proposed as key solution to reduce price volatility.',
    ],
    short_summary_es: [
      'SOFOFA: costos energeticos industriales en Chile son 35% superiores al promedio OCDE.',
      'Manufactura y mineria son los sectores mas afectados; pide redistribucion de cargos de transmision.',
      'El despliegue acelerado de almacenamiento a gran escala se propone como solucion clave.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },

  // ── Aurora Energy Research (Market Advisor) ──────────────
  {
    id: 'mock-aurora-001',
    title: 'Aurora: South American power markets to attract $180B in clean energy by 2030',
    title_es: 'Aurora: Mercados electricos de Sudamerica atraeran US$180.000M en energia limpia al 2030',
    source: 'Aurora Energy Research',
    source_type: 'Market Advisor',
    location: 'Global',
    category: 'Energy',
    date: d(3),
    url: 'https://www.auroraer.com/insight/south-america-clean-energy-2030',
    extended_description: 'Aurora Energy Research projects South American power markets will attract $180 billion in clean energy investment through 2030, led by Chile, Brazil, and Colombia. The firm identifies Chile as the highest-return market due to its exceptional solar resources in the Atacama and maturing regulatory framework. Aurora forecasts Chilean wholesale power prices to remain among the lowest in the region through 2035, supporting data center and mining electrification.',
    extended_description_es: 'Aurora Energy Research proyecta que los mercados electricos de Sudamerica atraeran US$180.000 millones en inversion en energia limpia hasta 2030, liderados por Chile, Brasil y Colombia.',
    short_summary: [
      'Aurora projects $180B clean energy investment in South America through 2030, led by Chile, Brazil, Colombia.',
      'Chile rated highest-return market due to Atacama solar resources and maturing regulatory framework.',
      'Chilean wholesale power prices forecast to remain among region\'s lowest through 2035.',
    ],
    short_summary_es: [
      'Aurora proyecta US$180.000M en inversion en energia limpia en Sudamerica hasta 2030.',
      'Chile es el mercado de mayor retorno por sus recursos solares en Atacama y marco regulatorio maduro.',
      'Los precios mayoristas de electricidad en Chile se mantendran entre los mas bajos de la region hasta 2035.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },

  // ── Ember (Market Advisor) ───────────────────────────────
  {
    id: 'mock-ember-001',
    title: 'Ember: Global electricity from clean sources hits 40% for first time in 2024',
    title_es: 'Ember: La electricidad global de fuentes limpias alcanza el 40% por primera vez en 2024',
    source: 'Ember',
    source_type: 'Market Advisor',
    location: 'Global',
    category: 'Energy',
    date: d(1),
    url: 'https://ember-energy.org/latest-insights/global-electricity-review-2024',
    extended_description: 'Ember\'s Global Electricity Review 2024 finds that clean sources — solar, wind, nuclear, and hydro — generated 40% of global electricity for the first time on record. Solar alone grew 23% year-on-year to become the fastest-growing power source for the 19th consecutive year. The report highlights that solar and wind together now exceed gas generation globally, a milestone reached five years ahead of most forecasts.',
    extended_description_es: 'El Global Electricity Review 2024 de Ember concluye que las fuentes limpias generaron el 40% de la electricidad mundial por primera vez. La solar crecio un 23% interanual, siendo la fuente mas rapida por 19 anos consecutivos.',
    short_summary: [
      'Ember: clean power hits 40% of global electricity in 2024 for the first time on record.',
      'Solar grew 23% YoY and is the world\'s fastest-growing electricity source for 19 consecutive years.',
      'Solar and wind together now exceed global gas generation — five years ahead of most forecasts.',
    ],
    short_summary_es: [
      'Ember: las fuentes limpias alcanzan el 40% de la electricidad global en 2024 por primera vez.',
      'La solar crecio 23% interanual y es la fuente de mas rapido crecimiento por 19 anos consecutivos.',
      'Solar y eolica juntas superan a la generacion global a gas, cinco anos antes de las proyecciones.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },

  // ── Lazard (Market Advisor) ──────────────────────────────
  {
    id: 'mock-lazard-001',
    title: 'Lazard LCOE 2024: Utility solar and wind remain cheapest sources of new power generation',
    title_es: 'Lazard LCOE 2024: Solar y eolica siguen siendo las fuentes mas baratas de nueva generacion',
    source: 'Lazard',
    source_type: 'Market Advisor',
    location: 'Global',
    category: 'Energy',
    date: d(5),
    url: 'https://www.lazard.com/research-insights/2024-levelized-cost-of-energy-plus',
    extended_description: 'Lazard\'s 17th annual Levelized Cost of Energy analysis finds utility-scale solar and onshore wind remain the least-cost options for new electricity generation in most markets, with solar at $24-96/MWh and wind at $27-73/MWh. The report notes that battery storage costs have declined 90% over the past decade and are now enabling round-the-clock renewable power at costs competitive with natural gas peakers.',
    extended_description_es: 'El analisis LCOE de Lazard encuentra que la solar y la eolica terrestre siguen siendo las opciones de menor costo para nueva generacion en la mayoria de los mercados, con solar a US$24-96/MWh.',
    short_summary: [
      'Lazard LCOE 2024: utility solar ($24-96/MWh) and onshore wind ($27-73/MWh) remain cheapest new power.',
      'Battery storage costs fell 90% over the past decade, enabling cost-competitive 24/7 renewable power.',
      'New gas peakers now more expensive than solar-plus-storage in most US and European markets.',
    ],
    short_summary_es: [
      'Lazard LCOE 2024: solar de escala (US$24-96/MWh) y eolica terrestre (US$27-73/MWh) son las mas baratas.',
      'Los costos de baterias cayeron 90% en la ultima decada, habilitando renovables 24/7 competitivas.',
      'Las centrales a gas pico son mas caras que solar+almacenamiento en EE.UU. y Europa.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },

  // ── BloombergNEF (Market Advisor) ───────────────────────
  {
    id: 'mock-bnef-001',
    title: 'BloombergNEF: Energy transition investment reaches record $1.8 trillion in 2023',
    title_es: 'BloombergNEF: La inversion en transicion energetica alcanza un record de US$1,8 billones en 2023',
    source: 'BloombergNEF',
    source_type: 'Market Advisor',
    location: 'Global',
    category: 'Energy',
    date: d(4),
    url: 'https://about.bnef.com/energy-transition-investment',
    extended_description: 'BloombergNEF\'s Energy Transition Investment Trends report finds global investment in the energy transition reached a record $1.8 trillion in 2023, more than double the level five years earlier. Solar dominated with $393 billion deployed, followed by EVs at $634 billion. The report highlights that for the first time, energy transition investment exceeded fossil fuel supply investment on a global basis.',
    extended_description_es: 'El informe de BloombergNEF concluye que la inversion global en transicion energetica alcanzo un record de US$1,8 billones en 2023, mas del doble del nivel de hace cinco anos. La solar domino con US$393.000 millones.',
    short_summary: [
      'BloombergNEF: global energy transition investment hits record $1.8T in 2023, doubling in five years.',
      'EVs led at $634B invested; solar second at $393B — both surpassing all previous annual records.',
      'For the first time, energy transition investment globally exceeded fossil fuel supply investment.',
    ],
    short_summary_es: [
      'BloombergNEF: la inversion global en transicion energetica alcanza un record de US$1,8 billones en 2023.',
      'Los VE lideraron con US$634.000M; la solar segunda con US$393.000M, ambos en records historicos.',
      'Por primera vez, la inversion en transicion supero a la inversion en suministro de combustibles fosiles.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },

  // ── Wood Mackenzie (Market Advisor) ─────────────────────
  {
    id: 'mock-woodmac-001',
    title: 'Wood Mackenzie: Data center power demand to add 100 GW of new capacity need by 2030',
    title_es: 'Wood Mackenzie: La demanda de centros de datos requerira 100 GW adicionales de nueva capacidad al 2030',
    source: 'Wood Mackenzie',
    source_type: 'Market Advisor',
    location: 'Global',
    category: 'Data Centers',
    date: d(2),
    url: 'https://www.woodmac.com/reports/power-markets-data-center-power-demand-2030',
    extended_description: 'Wood Mackenzie\'s latest power market analysis projects data center electricity demand will require 100 GW of dedicated new generation capacity globally by 2030, driven primarily by AI training and inference workloads. The firm finds hyperscalers are increasingly contracting directly with developers for dedicated renewable capacity, bypassing spot markets and creating a two-tier power procurement landscape.',
    extended_description_es: 'Wood Mackenzie proyecta que la demanda electrica de centros de datos requerira 100 GW de nueva capacidad de generacion dedicada globalmente al 2030, impulsada principalmente por cargas de trabajo de IA.',
    short_summary: [
      'Wood Mackenzie projects data center power demand requiring 100 GW of new dedicated capacity by 2030.',
      'AI training and inference workloads are the primary driver of accelerating data center electricity demand.',
      'Hyperscalers bypass spot markets, contracting directly with developers for dedicated renewable capacity.',
    ],
    short_summary_es: [
      'Wood Mackenzie proyecta que la demanda de centros de datos requerira 100 GW de nueva capacidad al 2030.',
      'Las cargas de trabajo de entrenamiento e inferencia de IA son el principal motor de la demanda creciente.',
      'Los hiperescaladores evitan el mercado spot contratando directamente capacidad renovable dedicada.',
    ],
    created_at: new Date().toISOString(),
    processed: true,
  },

]
